name: Docker Image CI

on:
  push:
    branches: 
      - "*"
  pull_request:
    branches:
      - "*"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Lint and Test
      run: |
        npm install
        npm run lint
        npm test
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --rm -t "quay.io/razee/remoteresource:${GITHUB_SHA}"
        echo "${QUAY_TOKEN}" | docker login -u="${QUAY_ID}" --password-stdin quay.io
        docker push "quay.io/razee/remoteresource:${GITHUB_SHA}
