name: Docker Image CI

on:
  push:
    branches: 
      - "*"
  pull_request:
    branches:
      - "*"

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: sh
    steps:
    - uses: actions/checkout@v2
    - name: Lint and Test
      run: |
        npm install
        npm run lint
        npm test
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --rm -t "quay.io/razee/remoteresource:${GITHUB_SHA}"

