name: Docker Image CI

on:
  push:
    branches: 
      - "*"
  pull_request:
    branches:
      - "*"


#on:
  #release:
    #types: [published]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
         docker build . --file Dockerfile --rm -t "quay.io/razee/remoteresource:${GITHUB_SHA}"
         docker images
         ./build/process-template.sh kubernetes/RemoteResource/resource.yaml >/tmp/resource.yaml
        
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: git config user.email "${NPMJS_EMAIL}"
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: "${NPMJS_API_KEY}"
